# Generated by Django 5.1.3 on 2024-11-19 05:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0003_alter_room_options"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="room",
            options={"ordering": ["updated", "created"]},
        ),
    ]
