# Generated by Django 5.1.3 on 2024-12-06 07:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0006_tryform"),
    ]

    operations = [
        migrations.RenameField(
            model_name="topic",
            old_name="top_name",
            new_name="name",
        ),
    ]
